let TESLA;

MIMachineEvents.registerRecipeTypes(event => {
    TESLA = event.register('tesla')
        .withItemInputs()
        .withItemOutputs()
        .withFluidInputs()
})

MIMachineEvents.registerCasings(event => {
    event.registerBlockImitation(
        'tesla',
        'betterblockz:ironslate_blockz_23'
    )
})

MIMachineEvents.registerMachines(event => {
    const customMachineShape = event.layeredShape("tesla", [
        ["      aaaaa      ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                b"],
        ["    aaaaaaaaa    ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "       ccc       ", "      ccccc      ", "       ccc       ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 "],
        ["   aaaaaaaaaaa   ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "        d        ", "     ccccccc     ", "    cc ccc cc    ", "     ccccccc     ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "      ccccc      ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "       bbb       ", "      bbbbb      ", "       bbb       "],
        ["  aaaaaaaaaaaaa  ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "      efffe      ", "      fffff      ", "      fffff      ", "      fffff      ", "      efffe      ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "   ccccccccbcc   ", "   c  ccccc  c   ", "   ccccccccccc   ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "      efffe      ", "      fffff      ", "      fffff      ", "      fffff      ", "      efffe      ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "    ccccccccc    ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "     bbbbbbb     ", "    bb     bb    ", "     bbbbbbb     "],
        [" aaaaaaaaaaaaaaa ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    deg   ged    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    deg   ged    ", "    de     ed    ", "   ccc     cbc   ", "  c  c     c  c  ", "   cccg   gccc   ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de  g  ed    ", "    de     ed    ", "    de     ed    ", "   ccccccccccc   ", "        d        ", "        d        ", "        d        ", "       eee       ", "                 ", "                 ", "                 ", "    bbbbbbbbb    ", "   b   bbb   b   ", "    bbbbbbbbb    "],
        [" aaaaaaaaaaaaaaa ", "    e       e    ", "    e       e    ", "    e  h h  e    ", "    e gi ig e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e gi ig e    ", "    e  h h  e    ", "  ccc       ccc  ", "  c c  h h  c c  ", "  ccc gi ig ccc  ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  h h  e    ", "    e       e    ", "    e   h   e    ", "    e   i   e    ", "    e   i   e    ", "    e   i   e    ", "    e   h   e    ", "   ccccccccccc   ", "     d     d     ", "     d     d     ", "     d     d     ", "     deeeeed     ", "     d     d     ", "                 ", "                 ", "   bbb     bbb   ", "   b  b   b  b   ", "   bbb     bbb   "],
        ["aaaaaaaaaaaaaaaaa", "   e  g   g  e   ", "   e  g   g  e   ", "   e  gi ig  e   ", "   eggkkkkkgge   ", "   f  kkkkk  f   ", "   f  kkkkk  f   ", "   f  kkkkk  f   ", "   e  kkkkk  e   ", "   e  kkkkk  e   ", "   eggkkkkkgge   ", "   e  gi ig  e   ", "  cc  g   g  cc  ", " c c  gi ig  c c ", "  ccgglllllggcc  ", "   e  lmmml  e   ", "   e  lmmml  e   ", "   e  lmmml  e   ", "   e  lllll  e   ", "   f   i i   f   ", "   f         f   ", "   f         f   ", "   e         e   ", "   e         e   ", "   e         e   ", "   e         e   ", "  ccccccccccccc  ", "                 ", "                 ", "                 ", "     eeeeeee     ", "      d   d      ", "      d   d      ", "      d   d      ", "   bb d   d bb   ", "  b  bb   bb  b  ", "   bb       bb   "],
        ["aaaaaaaaaaaaaaaaa", "   e         e   ", "   e         e   ", "   e hihihih e   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   e ikkkkki e   ", "   e ikkkkki e   ", "   e hihihih e   ", " ccc         ccc ", " ccc   i i   ccc ", " ccc  llnll  ccc ", "   e  mo om  e   ", "   e  mo om  e   ", "   e  mo om  e   ", "   f  lllll  f   ", "   f   i i   f   ", "   f         f   ", "   f         f   ", "   f         f   ", "   e         e   ", "   e         e   ", "   e         e   ", "  ccccccccccccc  ", "                 ", "                 ", "                 ", "    eeeeeeeee    ", "                 ", "                 ", "                 ", "  bbb       bbb  ", "  b b       b b  ", "  bbb       bbb  "],
        ["aaaaaaaaaaaaaaaaa", "  de         ed  ", "  de         ed  ", "  de   i i   ed  ", "  df  kkkkk  fd  ", "  df  kkkkk  fd  ", "  df  kkkkk  fd  ", "  df  kkkkk  fd  ", "  df  kkkkk  fd  ", "  de  kkkkk  ed  ", "  de  kkkkk  ed  ", "  de   i i   ed  ", " ccc         ccc ", " ccc   i i   ccc ", " ccc  lllll  ccc ", "   e  mooom  e   ", "   e  mooom  e   ", "   e  mooom  e   ", "   f  lllll  f   ", "   f   i i   f   ", "   f         f   ", "   f         f   ", "   f         f   ", "   e         e   ", "   e         e   ", "   e         e   ", "  ccccccccccccc  ", "    d       d    ", "    d       d    ", "    d       d    ", "    eeeeeeeee    ", "                 ", "                 ", "                 ", "  bbb       bbb  ", "  b b       b b  ", "  bbb       bbb  "],
        ["aaaaaaaaaaaaaaaaa", "   e         e   ", "   e         e   ", "   e hihihih e   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   f ikkkkki f   ", "   e ikkkkki e   ", "   e ikkkkki e   ", "   e hihihih e   ", " ccc         ccc ", " ccc   i i   ccc ", " ccc  llnll  ccc ", "   e  mo om  e   ", "   e  mo om  e   ", "   e  mo om  e   ", "   f  lllll  f   ", "   f   i i   f   ", "   f         f   ", "   f         f   ", "   f         f   ", "   e         e   ", "   e         e   ", "   e         e   ", "  ccccccccccccc  ", "                 ", "                 ", "                 ", "    eeeeeeeee    ", "                 ", "                 ", "                 ", "  bbb       bbb  ", "  b b       b b  ", "  bbb       bbb  "],
        ["aaaaaaaaaaaaaaaaa", "   e  g   g  e   ", "   e  g   g  e   ", "   e  gi ig  e   ", "   eggkkkkkgge   ", "   f  kkkkk  f   ", "   f  kkkkk  f   ", "   f  kkkkk  f   ", "   e  kkkkk  e   ", "   e  kkkkk  e   ", "   eggkkkkkgge   ", "   e  gi ig  e   ", "  cc  g   g  cc  ", " c c  gi ig  c c ", "  ccgglllllggcc  ", "   e  lmmml  e   ", "   e  lmmml  e   ", "   e  lmmml  e   ", "   e  lllll  e   ", "   f   i i   f   ", "   f         f   ", "   f         f   ", "   e         e   ", "   e         e   ", "   e         e   ", "   e         e   ", "  ccccccccccccc  ", "                 ", "                 ", "                 ", "     eeeeeee     ", "      d   d      ", "      d   d      ", "      d   d      ", "   bb d   d bb   ", "  b  bb   bb  b  ", "   bb       bb   "],
        [" aaaaaaaaaaaaaaa ", "    e       e    ", "    e   h   e    ", "    e  h h  e    ", "    e gi ig e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e gi ig e    ", "    e  h h  e    ", "  ccc       ccc  ", "  c c  h h  c c  ", "  ccc gi ig ccc  ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  i i  e    ", "    e  h h  e    ", "    e       e    ", "    e       e    ", "    e       e    ", "    e       e    ", "    e       e    ", "    e       e    ", "   ccccccccccc   ", "     d     d     ", "     d     d     ", "     d     d     ", "     deeeeed     ", "     d     d     ", "                 ", "                 ", "   bbb     bbb   ", "   b  b   b  b   ", "   bbb     bbb   "],
        [" aaaaaaaaaaaaaaa ", "    de     ed    ", "    de  i  ed    ", "    de     ed    ", "    deg   ged    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    deg   ged    ", "    de     ed    ", "   cbc     cbc   ", "  c  c     c  c  ", "   cccg   gccc   ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "    de     ed    ", "   ccccccccccc   ", "        d        ", "        d        ", "        d        ", "       eee       ", "                 ", "                 ", "                 ", "    bbbbbbbbb    ", "   b   bbb   b   ", "    bbbbbbbbb    "],
        ["  aaaaaaaaaaaaa  ", "      eeeee      ", "      eeiee      ", "      eeeee      ", "      efffe      ", "      fffff      ", "      fffff      ", "      fffff      ", "      efffe      ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "   ccccccccccc   ", "   c  ccccc  c   ", "   ccccccccccc   ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "      efffe      ", "      fffff      ", "      fffff      ", "      fffff      ", "      efffe      ", "      eeeee      ", "      eeeee      ", "      eeeee      ", "    ccccccccc    ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "     bbbbbbb     ", "    bb     bb    ", "     bbbbbbb     "],
        ["   aaaaaaaaaaa   ", "       aaa       ", "       aaa       ", "       a#a       ", "       aaa       ", "       aaa       ", "        a        ", "       aaa       ", "       aaa       ", "       aaa       ", "       aaa       ", "       aaa       ", "     ccccccc     ", "    cc ccc cc    ", "     ccccccc     ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "      ccccc      ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "       bbb       ", "      bbbbb      ", "       bbb       "],
        ["    aaaaaaaaa    ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "       ccc       ", "      ccccc      ", "       ccc       ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 "],
        ["a     aaaaa      ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 ", "                 "],
    ])
    .key("a", event.memberOfBlock("betterblockz:ironslate_blockz_23"), event.noHatch())
    .key("b", event.memberOfBlock("modern_industrialization:kanthal_coil"), event.noHatch())
    .key("c", event.memberOfBlock("modern_industrialization:advanced_machine_hull"), event.noHatch())
    .key("d", event.memberOfBlock("tfmg:steel_truss"), event.noHatch())
    .key("e", event.memberOfBlock("modern_industrialization:clean_stainless_steel_machine_casing"), event.noHatch())
    .key("f", event.memberOfBlock("modern_industrialization:stainless_steel_machine_casing_pipe"), event.noHatch())
    .key("g", event.memberOfBlock("electroenergetics:insulator"), event.noHatch())
    .key("h", event.memberOfBlock("allthecompressed:copper_block_2x"), event.noHatch())
    .key("i", event.memberOfBlock("blocksyouneed_luna:waxed_copper_coil"), event.noHatch())
    .key("k", event.memberOfBlock("minecraft:iron_block"), event.noHatch())
    .key("l", event.memberOfBlock("mekanism:induction_casing"), event.noHatch())
    .key("m", event.memberOfBlock("yet_another_industrialization:battery_casing"), event.noHatch())
    .key("n", event.memberOfBlock("mekanism:elite_induction_provider"), event.noHatch())
    .key("o", event.memberOfBlock("mekanism:elite_induction_cell"), event.noHatch())
    .build();

    event.simpleElectricCraftingMultiBlock(
        'Tesla',
        'tesla',
        TESLA,
        customMachineShape,
        event.progressBar(105, 35, 'arrow'),
        itemInputs => itemInputs.addSlots(42, 15, 3, 3),
        itemOutputs => itemOutputs.addSlot(139, 35),
        fluidInputs => fluidInputs.addSlot(14, 35),
        fluidOutputs => {},
        'tesla',
        'tesla',
        true,
        false,
        false
    )
});
